server:
  #rootPath: /api/*
  #applicationContextPath: /
  #adminContextPath: /
  applicationConnectors:
    - type: http
      port: 3828
  adminConnectors:
    - type: http
      port: 3829

atlasdb:
  keyValueService:
    type: memory
  targetedSweep:
    enableSweepQueueWrites: true
  namespace: atlasete

atlasDbRuntime:
  sweep:
    enabled: false
  targetedSweep:
    enabled: true
    shards: 1
  timelockRuntime:
    serversList:
      servers:
        - 'http://timelock:8421'
      sslConfiguration:
        keyStorePath: "var/security/keyStore.jks"
        keyStorePassword: "keystore"
        trustStorePath: "var/security/trustStore.jks"
